quarkus.http.validation.enable=true
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.redis.hosts=redis://localhost:6379
quarkus.redis.timeout=30s
quarkus.redis.max-pool-size=10
quarkus.redis.max-pool-waiting=10
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
